### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by FudongGe** [chengweialan/DeSiRe-GS#2]
Hi, thanks for your great work!

And could you please share how Figure 1 in the paper is visualized (such as the Gaussians)? For example, what code is used?

**Comment by chengweialan** [comment]
For the visualization of Gaussians, we use SIBR viewer, the same as [3DGS](https://github.com/graphdeco-inria/gaussian-splatting). You can refer to [this page](https://github.com/graphdeco-inria/gaussian-splatting?tab=readme-ov-file#interactive-viewers) for installation details.
